// <auto-generated />
using ContactList.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactListDatastar.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20260407171859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactList.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Work",
                            Email = "alice@example.com",
                            Name = "Alice Smith",
                            Notes = "Project manager",
                            Phone = "503-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Friend",
                            Email = "bob@example.com",
                            Name = "Bob Jones",
                            Phone = "503-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Family",
                            Email = "carol@example.com",
                            Name = "Carol White",
                            Notes = "Sister",
                            Phone = "503-555-0103"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
